markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Skhizein'X"
markdown: kramdown

author: "skhizein"
atom-baseurl: ""

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://www.flickr.com/photos/134804491@N07/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
